// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pkbskaocgqfidpuiiieo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBrYnNrYW9jZ3FmaWRwdWlpaWVvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTczMjg4MzQsImV4cCI6MjA3MjkwNDgzNH0.pUHp8ekY0h2UP24Vfkw5CO-2wI93bmX5j0VvAefVaKE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});